apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: app
spec:
  secretName: app
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: demo.cloud-personal.com
  dnsNames:
  - demo.cloud-personal.com
  